DROP ALL OBJECTS;

CREATE TABLE departamento (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE funcionarios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(60)  NOT NULL,
    apellido          VARCHAR(60)  NOT NULL,
    edad              INTEGER,
    fecha_nacimiento  DATE         NOT NULL,
    fecha_ingreso     DATE         NOT NULL,
    foto              BYTEA,
    fecha_ult_modif   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    legajo            INTEGER      NOT NULL,
    departamento_id   INTEGER      REFERENCES departamento(id) ON DELETE SET NULL
);
CREATE INDEX idx_funcionarios_apellido_nombre ON funcionarios (apellido, nombre);

CREATE TABLE movimiento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id  BIGINT NOT NULL REFERENCES funcionarios(id),
    tipo            VARCHAR(10) NOT NULL,
    monto           NUMERIC(15,2) NOT NULL,
    fecha_hora      TIMESTAMP NOT NULL,
    descripcion     VARCHAR(500)
);

CREATE TABLE proyecto (
    codigo  VARCHAR(10),
    anio    INTEGER,
    titulo  VARCHAR(120) NOT NULL,
    PRIMARY KEY (codigo, anio)
);

CREATE TABLE asignacion_proyecto (
    funcionario_id   BIGINT      NOT NULL REFERENCES funcionarios(id),
    proyecto_codigo  VARCHAR(10) NOT NULL,
    proyecto_anio    INTEGER     NOT NULL,
    horas            NUMERIC(6,1),
    PRIMARY KEY (funcionario_id, proyecto_codigo, proyecto_anio),
    CONSTRAINT fk_asignacion_proyecto FOREIGN KEY (proyecto_codigo, proyecto_anio)
        REFERENCES proyecto (codigo, anio) ON UPDATE CASCADE
);

-- Tabla sin PK ni FK ni índices, con nombre que requiere comillas
CREATE TABLE "Log Eventos" (
    "Mensaje" VARCHAR(200)
);
