-- Ajusta una base EXISTENTE para que funcionen los ejemplos del curso
-- (ejemplos.Main -> FuncionarioDao y TransferenciaService).
-- NO borra tablas ni datos: sólo crea lo que no existe y agrega las columnas que falten.
-- Se puede ejecutar varias veces sin problema.
--
-- Uso: psql -h localhost -p 5435 -U postgres -d ucsajava -f db/ajustar_tablas_ejemplo.sql
-- (o abrirlo en pgAdmin / DBeaver y ejecutarlo completo)

CREATE TABLE IF NOT EXISTS funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Columnas que usa FuncionarioDao.insertar(...)
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS id               BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS nombre           VARCHAR(60);
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS apellido         VARCHAR(60);
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS edad             INTEGER;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_ingreso    DATE;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS foto             BYTEA;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_ult_modif  TIMESTAMP;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS legajo           INTEGER;

-- Tablas que usa TransferenciaService
CREATE TABLE IF NOT EXISTS cuenta_funcionario (
    id              BIGSERIAL PRIMARY KEY,
    funcionario_id  BIGINT NOT NULL UNIQUE REFERENCES funcionarios(id),
    saldo           NUMERIC(15,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS movimiento (
    id              BIGSERIAL PRIMARY KEY,
    funcionario_id  BIGINT NOT NULL REFERENCES funcionarios(id),
    tipo            VARCHAR(10) NOT NULL,
    monto           NUMERIC(15,2) NOT NULL,
    fecha_hora      TIMESTAMP NOT NULL,
    descripcion     TEXT
);
