package py.edu.ucsa.jdbc.tx.demo;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Random;

import javax.sql.DataSource;

import py.edu.ucsa.jdbc.tx.Database;

/**
 * Carga datos de demostración para el Database Inspector.
 * <p>
 * Crea tablas con prefijo {@code tp_} (y una llamada {@code "TP Auditoria"}) que
 * usan todo lo que el inspector debe mostrar: columnas autoincrementales (SERIAL e
 * IDENTITY), columnas NULL y NOT NULL, tipos con tamaño y decimales, clave primaria
 * simple y compuesta, claves foráneas simples y compuestas con distintas reglas,
 * índices únicos, no únicos, de varias columnas y de expresión, tablas con más de
 * 10 registros y una tabla sin PK, FK ni índices.
 * <p>
 * <b>No toca ninguna otra tabla.</b> Si los datos ya están cargados no hace nada;
 * con el argumento {@code --recargar} vacía sólo las tablas {@code tp_} y las vuelve
 * a cargar. Los datos se insertan con operaciones batch dentro de una transacción.
 * <p>
 * Ejecutar: en STS, clic derecho → Run As → Java Application; o
 * {@code mvnw spring-boot:run -Dspring-boot.run.main-class=py.edu.ucsa.jdbc.tx.demo.PrepararDatos}
 */
public final class PrepararDatos {

	private static final int CATEGORIAS = 6;
	private static final int PRODUCTOS = 60;
	private static final int CLIENTES = 300;
	private static final int PEDIDOS = 5000;
	private static final int LINEAS_POR_PEDIDO = 3;
	private static final int DEVOLUCIONES = 200;
	private static final int LOTE = 1000;

	private static final String[] DDL = {
			"""
			CREATE TABLE IF NOT EXISTS tp_categoria (
			    id           SERIAL PRIMARY KEY,
			    nombre       VARCHAR(50) NOT NULL UNIQUE,
			    descripcion  TEXT
			)
			""",
			"""
			CREATE TABLE IF NOT EXISTS tp_producto (
			    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			    codigo        CHAR(8)       NOT NULL UNIQUE,
			    nombre        VARCHAR(120)  NOT NULL,
			    precio        NUMERIC(12,2) NOT NULL CHECK (precio >= 0),
			    stock         INTEGER       NOT NULL DEFAULT 0,
			    activo        BOOLEAN       NOT NULL DEFAULT TRUE,
			    imagen        BYTEA,
			    categoria_id  INTEGER REFERENCES tp_categoria(id) ON DELETE SET NULL
			)
			""",
			"CREATE INDEX IF NOT EXISTS idx_tp_producto_categoria_nombre ON tp_producto (categoria_id, nombre)",
			"""
			CREATE TABLE IF NOT EXISTS tp_cliente (
			    id          SERIAL PRIMARY KEY,
			    documento   VARCHAR(20)  NOT NULL UNIQUE,
			    nombre      VARCHAR(100) NOT NULL,
			    email       VARCHAR(150),
			    telefono    VARCHAR(30),
			    fecha_alta  DATE NOT NULL DEFAULT CURRENT_DATE
			)
			""",
			"CREATE UNIQUE INDEX IF NOT EXISTS idx_tp_cliente_email_lower ON tp_cliente (lower(email))",
			"""
			CREATE TABLE IF NOT EXISTS tp_pedido (
			    id           BIGSERIAL PRIMARY KEY,
			    cliente_id   INTEGER NOT NULL REFERENCES tp_cliente(id) ON UPDATE CASCADE ON DELETE RESTRICT,
			    fecha        TIMESTAMP   NOT NULL,
			    estado       VARCHAR(15) NOT NULL,
			    total        NUMERIC(14,2),
			    observacion  TEXT
			)
			""",
			"CREATE INDEX IF NOT EXISTS idx_tp_pedido_cliente_fecha ON tp_pedido (cliente_id, fecha DESC)",
			"CREATE INDEX IF NOT EXISTS idx_tp_pedido_estado ON tp_pedido (estado)",
			"""
			CREATE TABLE IF NOT EXISTS tp_detalle_pedido (
			    pedido_id        BIGINT   NOT NULL REFERENCES tp_pedido(id) ON DELETE CASCADE,
			    linea            SMALLINT NOT NULL,
			    producto_id      BIGINT   NOT NULL REFERENCES tp_producto(id),
			    cantidad         INTEGER  NOT NULL CHECK (cantidad > 0),
			    precio_unitario  NUMERIC(12,2) NOT NULL,
			    PRIMARY KEY (pedido_id, linea)
			)
			""",
			"CREATE INDEX IF NOT EXISTS idx_tp_detalle_producto ON tp_detalle_pedido (producto_id)",
			"""
			CREATE TABLE IF NOT EXISTS tp_devolucion (
			    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			    pedido_id  BIGINT   NOT NULL,
			    linea      SMALLINT NOT NULL,
			    motivo     VARCHAR(200),
			    fecha      DATE NOT NULL,
			    CONSTRAINT fk_tp_devolucion_detalle FOREIGN KEY (pedido_id, linea)
			        REFERENCES tp_detalle_pedido (pedido_id, linea) ON UPDATE CASCADE ON DELETE CASCADE
			)
			""",
			"""
			CREATE TABLE IF NOT EXISTS "TP Auditoria" (
			    "Momento"  TIMESTAMP NOT NULL,
			    "Usuario"  VARCHAR(40),
			    "Mensaje"  VARCHAR(200)
			)
			"""
	};

	private static final String[] ESTADOS = { "PENDIENTE", "PAGADO", "ENVIADO", "ENTREGADO", "CANCELADO" };
	private static final String[] CATEGORIAS_NOMBRES = { "Almacén", "Bebidas", "Limpieza", "Electrónica", "Librería", "Ferretería" };

	private PrepararDatos() {
	}

	public static void main(String[] args) throws SQLException {
		boolean recargar = args.length > 0 && "--recargar".equals(args[0]);
		try {
			preparar(Database.getDataSource(), recargar);
		} finally {
			Database.cerrarPool();
		}
	}

	public static void preparar(DataSource dataSource, boolean recargar) throws SQLException {
		try (Connection conn = dataSource.getConnection()) {
			System.out.println("Base: " + conn.getMetaData().getURL());
			conn.setAutoCommit(false);
			try (Statement st = conn.createStatement()) {
				for (String sql : DDL) {
					st.execute(sql);
				}
				if (recargar) {
					System.out.println("Vaciando las tablas tp_ ...");
					st.execute("TRUNCATE tp_devolucion, tp_detalle_pedido, tp_pedido, tp_cliente, tp_producto, tp_categoria, "
							+ "\"TP Auditoria\" RESTART IDENTITY CASCADE");
				}
				if (!recargar && tieneDatos(st)) {
					conn.commit();
					System.out.println("Los datos de demostración ya estaban cargados (use --recargar para volver a cargarlos).");
					mostrarResumen(conn);
					return;
				}
				cargar(conn);
				conn.commit();
			} catch (SQLException | RuntimeException e) {
				conn.rollback();
				throw e;
			}
			System.out.println("Datos de demostración cargados correctamente.");
			mostrarResumen(conn);
		}
	}

	private static boolean tieneDatos(Statement st) throws SQLException {
		try (ResultSet rs = st.executeQuery("SELECT EXISTS (SELECT 1 FROM tp_categoria)")) {
			rs.next();
			return rs.getBoolean(1);
		}
	}

	private static void cargar(Connection conn) throws SQLException {
		Random r = new Random(2026);
		LocalDate hoy = LocalDate.of(2026, 9, 1);

		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO tp_categoria (nombre, descripcion) VALUES (?, ?)")) {
			for (int i = 0; i < CATEGORIAS; i++) {
				ps.setString(1, CATEGORIAS_NOMBRES[i]);
				// una categoría queda con descripción NULL a propósito
				if (i == CATEGORIAS - 1) {
					ps.setNull(2, java.sql.Types.VARCHAR);
				} else {
					ps.setString(2, "Productos de " + CATEGORIAS_NOMBRES[i].toLowerCase());
				}
				ps.addBatch();
			}
			ps.executeBatch();
		}

		BigDecimal[] precios = new BigDecimal[PRODUCTOS + 1];
		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO tp_producto (codigo, nombre, precio, stock, activo, imagen, categoria_id) VALUES (?, ?, ?, ?, ?, ?, ?)")) {
			for (int i = 1; i <= PRODUCTOS; i++) {
				precios[i] = BigDecimal.valueOf(1000 + r.nextInt(250_000)).setScale(2, RoundingMode.HALF_UP);
				ps.setString(1, String.format("PR%06d", i));
				ps.setString(2, "Producto " + i);
				ps.setBigDecimal(3, precios[i]);
				ps.setInt(4, r.nextInt(500));
				ps.setBoolean(5, i % 10 != 0);
				if (i % 7 == 0) {
					byte[] imagen = new byte[64 + r.nextInt(64)];
					r.nextBytes(imagen);
					ps.setBytes(6, imagen);
				} else {
					ps.setNull(6, java.sql.Types.BINARY);
				}
				if (i % 15 == 0) {
					ps.setNull(7, java.sql.Types.INTEGER);
				} else {
					ps.setInt(7, 1 + (i % CATEGORIAS));
				}
				ps.addBatch();
			}
			ps.executeBatch();
		}

		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO tp_cliente (documento, nombre, email, telefono, fecha_alta) VALUES (?, ?, ?, ?, ?)")) {
			for (int i = 1; i <= CLIENTES; i++) {
				ps.setString(1, String.valueOf(1_000_000 + i * 37));
				ps.setString(2, "Cliente " + i);
				ps.setString(3, i % 9 == 0 ? null : "cliente" + i + "@correo.com.py");
				ps.setString(4, i % 4 == 0 ? null : "0981" + String.format("%06d", i));
				ps.setDate(5, Date.valueOf(hoy.minusDays(r.nextInt(1000))));
				ps.addBatch();
			}
			ps.executeBatch();
		}

		try (PreparedStatement pedido = conn.prepareStatement(
				"INSERT INTO tp_pedido (cliente_id, fecha, estado, total, observacion) VALUES (?, ?, ?, ?, ?)");
				PreparedStatement detalle = conn.prepareStatement(
						"INSERT INTO tp_detalle_pedido (pedido_id, linea, producto_id, cantidad, precio_unitario) VALUES (?, ?, ?, ?, ?)")) {
			for (int p = 1; p <= PEDIDOS; p++) {
				BigDecimal total = BigDecimal.ZERO;
				for (int l = 1; l <= LINEAS_POR_PEDIDO; l++) {
					int producto = 1 + r.nextInt(PRODUCTOS);
					int cantidad = 1 + r.nextInt(5);
					detalle.setLong(1, p);
					detalle.setShort(2, (short) l);
					detalle.setLong(3, producto);
					detalle.setInt(4, cantidad);
					detalle.setBigDecimal(5, precios[producto]);
					detalle.addBatch();
					total = total.add(precios[producto].multiply(BigDecimal.valueOf(cantidad)));
				}
				pedido.setInt(1, 1 + r.nextInt(CLIENTES));
				pedido.setTimestamp(2, Timestamp.valueOf(LocalDateTime.of(hoy, java.time.LocalTime.NOON)
						.minusMinutes(r.nextInt(500_000))));
				String estado = ESTADOS[r.nextInt(ESTADOS.length)];
				pedido.setString(3, estado);
				pedido.setBigDecimal(4, "CANCELADO".equals(estado) ? null : total);
				pedido.setString(5, p % 20 == 0 ? "Entregar por la tarde" : null);
				pedido.addBatch();
				if (p % LOTE == 0) {
					// primero los pedidos (el detalle los referencia)
					pedido.executeBatch();
					detalle.executeBatch();
				}
			}
			pedido.executeBatch();
			detalle.executeBatch();
		}

		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO tp_devolucion (pedido_id, linea, motivo, fecha) VALUES (?, ?, ?, ?)")) {
			for (int i = 1; i <= DEVOLUCIONES; i++) {
				ps.setLong(1, i * (PEDIDOS / DEVOLUCIONES));
				ps.setShort(2, (short) (1 + i % LINEAS_POR_PEDIDO));
				ps.setString(3, i % 3 == 0 ? null : "Producto dañado #" + i);
				ps.setDate(4, Date.valueOf(hoy.minusDays(i)));
				ps.addBatch();
			}
			ps.executeBatch();
		}

		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO \"TP Auditoria\" (\"Momento\", \"Usuario\", \"Mensaje\") VALUES (?, ?, ?)")) {
			String[] mensajes = { "Carga inicial de datos", "Alta de clientes", "Alta de productos", "Alta de pedidos", "Fin de la carga" };
			for (int i = 0; i < mensajes.length; i++) {
				ps.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now().plusSeconds(i)));
				ps.setString(2, i == 0 ? null : "sistema");
				ps.setString(3, mensajes[i]);
				ps.addBatch();
			}
			ps.executeBatch();
		}
	}

	private static void mostrarResumen(Connection conn) throws SQLException {
		String sql = """
				SELECT 'tp_categoria', count(*) FROM tp_categoria
				UNION ALL SELECT 'tp_producto', count(*) FROM tp_producto
				UNION ALL SELECT 'tp_cliente', count(*) FROM tp_cliente
				UNION ALL SELECT 'tp_pedido', count(*) FROM tp_pedido
				UNION ALL SELECT 'tp_detalle_pedido', count(*) FROM tp_detalle_pedido
				UNION ALL SELECT 'tp_devolucion', count(*) FROM tp_devolucion
				UNION ALL SELECT '"TP Auditoria"', count(*) FROM "TP Auditoria"
				""";
		try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
			System.out.println("Registros por tabla:");
			while (rs.next()) {
				System.out.printf("  %-20s %6d%n", rs.getString(1), rs.getLong(2));
			}
		}
	}
}
