package py.edu.ucsa.jdbc.tx.ejemplos;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

/**
 * Deja la base lista para los ejemplos (FuncionarioDao y TransferenciaService).
 * <p>
 * NO borra tablas ni datos: sólo crea las tablas que no existen y agrega a
 * {@code funcionarios} las columnas que falten. Se puede ejecutar siempre.
 * Es lo mismo que hace el script {@code db/ajustar_tablas_ejemplo.sql}.
 */
public final class PreparacionBase {

	private static final String[] SENTENCIAS = {
			"""
			CREATE TABLE IF NOT EXISTS funcionarios (
			    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
			)
			""",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS id               BIGINT GENERATED BY DEFAULT AS IDENTITY",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS nombre           VARCHAR(60)",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS apellido         VARCHAR(60)",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS edad             INTEGER",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_ingreso    DATE",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS foto             BYTEA",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS fecha_ult_modif  TIMESTAMP",
			"ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS legajo           INTEGER",
			"""
			CREATE TABLE IF NOT EXISTS cuenta_funcionario (
			    id              BIGSERIAL PRIMARY KEY,
			    funcionario_id  BIGINT NOT NULL UNIQUE REFERENCES funcionarios(id),
			    saldo           NUMERIC(15,2) NOT NULL DEFAULT 0
			)
			""",
			"""
			CREATE TABLE IF NOT EXISTS movimiento (
			    id              BIGSERIAL PRIMARY KEY,
			    funcionario_id  BIGINT NOT NULL REFERENCES funcionarios(id),
			    tipo            VARCHAR(10) NOT NULL,
			    monto           NUMERIC(15,2) NOT NULL,
			    fecha_hora      TIMESTAMP NOT NULL,
			    descripcion     TEXT
			)
			"""
	};

	private PreparacionBase() {
	}

	public static void asegurarTablas(DataSource dataSource) throws SQLException {
		try (Connection conn = dataSource.getConnection();
				Statement st = conn.createStatement()) {
			for (String sql : SENTENCIAS) {
				st.execute(sql);
			}
		}
	}
}
